# Generated by Django 2.2.26 on 2022-01-29 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=b'I01\n', serialize=False)),
                ('company_name', models.CharField(max_length=50)),
                ('nit', models.PositiveIntegerField()),
                ('code', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=b'I01\n', serialize=False)),
                ('document', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=b'I01\n', serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('attribute_4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bills_Products',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=b'I01\n', serialize=False)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Bills')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Products')),
            ],
        ),
        migrations.AddField(
            model_name='bills',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Clients'),
        ),
    ]
