# Generated by Django 2.2.26 on 2022-01-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220129_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.PositiveIntegerField(),
        ),
    ]
